"""update referral data

Revision ID: 28b0ffab6136
Revises: 83d366ded6ce
Create Date: 2026-05-26 20:54:20.382058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker

# revision identifiers, used by Alembic.
revision: str = '28b0ffab6136'
down_revision: Union[str, Sequence[str], None] = '83d366ded6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


async def upgrade_async() -> None:
    """Асинхронное обновление данных."""
    print("UPGRADE_ASYNC CALLED")

    from config import settings
    from database.services.data_seeder import DataSeeder
    from sqlalchemy.ext.asyncio import AsyncSession

    # Создаем асинхронное подключение
    database_url = settings.get_database_url()
    engine = create_async_engine(database_url)
    async_session = async_sessionmaker(engine, class_=AsyncSession)

    async with async_session() as session:
        seeder = DataSeeder(session)
        await seeder.update_seed_data()


def upgrade() -> None:
    print("Upgrade is in...")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import asyncio
    import nest_asyncio
    nest_asyncio.apply()
    asyncio.run(upgrade_async())
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
