"""added new promo code usage history and new column for user table

Revision ID: 4ec5686fe365
Revises: d012f1da8070
Create Date: 2026-06-04 22:26:49.139727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec5686fe365'
down_revision: Union[str, Sequence[str], None] = 'd012f1da8070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'user_id', name='unique_user_promo_usage')
    )
    op.alter_column('promo_codes', 'is_referral',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('users', sa.Column('pro_discount', sa.Integer(), nullable=True))
    op.alter_column('users', 'trial_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'trial_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'pro_discount')
    op.alter_column('promo_codes', 'is_referral',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('promo_code_usages')
    # ### end Alembic commands ###
