"""Added conditions for a new task

Revision ID: 589d223e655c
Revises: de50ad594d5c
Create Date: 2026-05-11 10:33:22.375483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker

# revision identifiers, used by Alembic.
revision: str = '589d223e655c'
down_revision: Union[str, Sequence[str], None] = 'de50ad594d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

async def upgrade_async() -> None:
    """Асинхронное обновление данных."""
    from config import settings
    from database.services.data_seeder import DataSeeder
    from sqlalchemy.ext.asyncio import AsyncSession

    # Создаем асинхронное подключение
    database_url = settings.get_database_url()
    engine = create_async_engine(database_url)
    async_session = async_sessionmaker(engine, class_=AsyncSession)

    async with async_session() as session:
        seeder = DataSeeder(session)
        await seeder.update_seed_data()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import asyncio
    asyncio.run(upgrade_async())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
