"""Added new column

Revision ID: 76d95aeff30b
Revises: 28b0ffab6136
Create Date: 2026-05-29 22:56:08.275665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d95aeff30b'
down_revision: Union[str, Sequence[str], None] = '28b0ffab6136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('promo_code_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'referrals', 'promo_codes', ['promo_code_id'], ['id'])
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_column('referrals', 'promo_code_id')
    # ### end Alembic commands ###
