"""create column referral code for users

Revision ID: 967f5ad862f1
Revises: 16b5d7838206
Create Date: 2026-05-22 23:48:10.840383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967f5ad862f1'
down_revision: Union[str, Sequence[str], None] = '16b5d7838206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
