"""added columns for promo_codes table

Revision ID: d012f1da8070
Revises: df9d8d388b7a
Create Date: 2026-05-31 22:55:51.070460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd012f1da8070'
down_revision: Union[str, Sequence[str], None] = 'df9d8d388b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('promo_codes', sa.Column('is_referral', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'promo_codes', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'trial_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'promo_codes', type_='foreignkey')
    op.drop_column('promo_codes', 'is_referral')
    op.drop_column('promo_codes', 'owner_id')
    # ### end Alembic commands ###
