"""trying update task table

Revision ID: de50ad594d5c
Revises: 042f735f0f7b
Create Date: 2026-05-11 10:21:32.830020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker

# revision identifiers, used by Alembic.
revision: str = 'de50ad594d5c'
down_revision: Union[str, Sequence[str], None] = '042f735f0f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


async def upgrade_async() -> None:
    """Асинхронное обновление данных."""
    from config import settings
    from database.services.data_seeder import DataSeeder
    from sqlalchemy.ext.asyncio import AsyncSession

    # Создаем асинхронное подключение
    database_url = settings.get_database_url()
    engine = create_async_engine(database_url)
    async_session = async_sessionmaker(engine, class_=AsyncSession)

    async with async_session() as session:
        seeder = DataSeeder(session)
        await seeder.update_seed_data()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
