"""added new column trial for user table

Revision ID: df9d8d388b7a
Revises: 76d95aeff30b
Create Date: 2026-05-31 22:28:45.972578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9d8d388b7a'
down_revision: Union[str, Sequence[str], None] = '76d95aeff30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_amount', sa.Integer(), nullable=True, default=1))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_amount')
    # ### end Alembic commands ###
